### PR TITLE
updated docs

### PR DESCRIPTION
**Pull request by rananna**

### CODE REVIEW

**Comment by casainho** [comment]
This is empty.

**Comment by rananna** [comment]
I have a pull bot implemented on my GitHub repo that automatically keeps the repo updated from your repo.
https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/wei/pull&ved=2ahUKEwj7vJ3978_tAhXGGFkFHSSmCO8QFjAAegQIDRAC&usg=AOvVaw234ZtE5XKKkPAntZ3h7UHC
Looks like it wiped out my changes for the PR!
I will uninstall this and try again.

**Comment by stsdc** [comment]
@rananna what bot are you using? I'm also interested in this. 😅

For every PR I recommend to create new branch. It is always safer to work on separate branch.

Also sorry for not fixing CI. These are hot pre- Christmas weeks at work.

**Comment by rananna** [comment]
https://probot.github.io/apps/pull/

**Pull request closed without merging**
