### PR TITLE
Power Breakthrough!

### PR DESCRIPTION
**Pull request by rananna**
@casainho ,
As you know, the power off current for the remote control is around 10uA, which should be suffficient for a CR2032 life of about a year. 
However, the spec for the NRF52840 SOC suggests that this should be less than 1ua.
I opened a ticket with nordic to discuss this issue and the result is documented in the attached pdf:
[(2) Nordic DevZone.PDF](https://github.com/OpenSourceEBike/ebike_wireless_remote/files/5781710/2.Nordic.DevZone.PDF)

The testing I was doing previously  was with SB1 shorted, and SB2 left intact. I did this because my assumption from the published schematics was this solder bridge was in place to prevent a user from connecting 5V to VBUS with SB1 shorted, which would fry the 52840 SOC by bypassing the first regulator. Since I never planned to use VBUS input, I never bothered to open this bridge, assuming that the VBUS input was now floating.

However, in discussions with Nordic, they also measured about 10uA in POWER OFF mode and we determined the following:
nordic

Although that is not obvious from the schematics published by Nordic, you can see the issue  in the updated  schematic Nordic  sent:
schematic

So, I tried measuring again with SB2 opened, and the current went from ~10uA to 0.44 uA!: (in line with the SOC spec)
deep_sleep

This implies a battery life of MUCH greater than 1 year as most of the battery loss for the remote will be  in POWER OFF mode.
29 months (!) in this simulation:
battery_life

It seems to me that there should be no reason to connect  VDDH for a 3v system that only uses the second regulator, and therefore it seems unnecessary to short SB1.  As the shorting of SB1 is a tricky soldering job for new users to do, I would like to leave it out of the instructions. It is a LOT easier for the user to open SB2 by scraping away the short with a razor blade or even a jewellers screwdriver. So, I posed the question to Nordic:
SB1

The answer suggests to me that it should be ok  to not short SB1.
I have tried without the SB1 short and it works fine. I think it should be fine to leave it out of the instructions.
I therefore  modified the instructions as follows:
life

Conclusion:
Even with lots of LED use during biking, we now have a remote that can easily work for a year on one CR2032 battery!

### CODE REVIEW

**Comment by stsdc** [comment]
Wow, that's amazing work @rananna! 🚴

**Comment by rananna** [comment]
Thanks. I am pleased to have found the issue.

**Comment by casainho** [comment]
Congratulations!! this is an important winning.

Are you able to measure the total current of the TSDZ2 wireless board? I think at some point we should need that value, at least to put on the documentation and let new users without worry about that, since it will be discharging the battery but should be very very low.

**Comment by rananna** [comment]
I am waiting to do these tests with the motor connected to the board. Have you found the issue causing burnout of the board and controller? Have you determined if the SOT223 transistors is working?  Is the circuit design finalized?
Once the design is confirmed working, I would like to solder a board and test the tsdz2 wireless connected to the motor.
I can then do pwr measurements under various scenarios.

**Comment by casainho** [comment]
I had one last STM8S105 dev board:
image

That I use to simulate the TSDZ2 motor. That board has a DC-DC converter and receives the power from the wireless board, so, turn on/off is correctly simulated and motor startup. I also tested on my EBike and seems to work as expected.

I had no more issues, because I am using a real battery to power the system and I only use mains power to power the PC, no more connections also the USB charger connected to mains power!!

Yes, the current circuit works very well!! The latest videos were with the circuit, that I am pretty sure is perfect. The only think is that I bought a different mosfet to try a bigger one since one of them is very small to solder (ok for me but others did complain).

I must say that I do not expect to change anything in:
- wireless remote hardware and firmware
- bootloader firmware
- TSDZ2 motor firmware - I am always using the stable V1.1.0
- TSDZ2 wireless board hardware
- TSDZ2 wireless board firmware (unless if anything is needed for ANT or low power improvement)

What I need to do is only on the Android app and is mostly visual details, otherwise it seems to be working very well. So please build your board and help to test. Maybe would be better if we both could focus now on using the mobile app only and when it will be minimum enough, then we could both start working and testing the wireless remote, because the idea is to replicate the commands, etc from the mobile app. As for the Garmin GPS, I do not expect much to change, I think everything is mostly working already.

**Comment by rananna** [comment]
Good news!
I will build a board for testing with the motor 
I would like to order the BSP296 in SOT223 as I also find the soldering challenging.
Have you confirmed that it is working?

**Comment by casainho** [comment]
I have not received the BSP296 yet, maybe I will in 3 or 4 weeks.

**Comment by rananna** [comment]
It should work, I will order it and give it a try.
I can get from digikey in a few days.

**Pull request merged**
