### PR TITLE
motor power control, motor error display, SOC display

### PR DESCRIPTION
**Pull request by rananna**
@casainho ,
This PR has the following changes:
1. motor state control implemented. A long press of the STANDBY key will turn the motor on/off. 
When the motor is initialising, the R &B  LEDS will slowly flash together creating an off-white color.
 When the motor is finally on, the off-white led will rapidly flash, followed 2 seconds later by a display of the motor battery state. 
If the motor is turning off, the battery state will also be displayed.
 Battery state is indicated by flashing the GREEN LED. The number of flashes will indicate battery charge state from from 1 flash (10% charge) to 10 flashes (100% charge).

2. Motor error states are indicated by the green power LED on the other side of the Nordic board. there are 3 error states:
a- motor initialization errors are indicated by a slowly flashing LED, 
b -firmware mismatch errors are indicated by a fast flashing LED,
c-  and configuration errors are indicated by a steady on LED.

All are tested and working fine.

### CODE REVIEW

**Comment by casainho** [comment]
@rananna, sorry but I just joined the sources of the bootloader, wireless board and wireless remote, this way we have only one common sources. Now there is only one place where the folder of Nordic SDK and not replicated 3 times.

For instance, recently you created the led_pwm_on() on the remote only but now it can be moved outside to common_firmware folder and then reuse on all the projects, like I will need it for the wireless board.

Get it here and please stop use the other repos, that I can make in archive mode soon: https://github.com/OpenSourceEBike/TSDZ2_wireless

**Comment by rananna** [comment]
Are you sure that this will not create a problem.
There were differences in the nordic sdk settings between the bootloader and the wireless remote.
Will this be properly handled?

**Comment by casainho** [comment]
It is supposed to be a code that is not changed, to be the same SDK. The config file of SDK is on each project include folder.

I built every project and I flashed and did run.

**Comment by stsdc** [comment]
In such a case I would move SDK to separate repo and made it a submodule to every repo as it is a dependency. But even such a scheme is not really good solution and I would stick to what @charliebruce proposed once with a docker container. SDK shouldn't be in a repo at all.

**Comment by casainho** [comment]
@rananna is it working for you? anything I can help you?

**Comment by rananna** [comment]
I have imported the state change code into the new repository and will test if everything is still working today. If all is well I will submit a PR.

**Comment by rananna** [comment]
Unfortunately, after re-compiling with the new code, the remote is constantly resetting for some reason.
There has been some change, but it is not clear to me what it is.
I do not have time to figure this out today, so the PR will have to wait.

**Comment by rananna** [comment]
can you do a file compare on  the sdk version in the old repo with the new repo?
Maybe I changed something in the past.

**Comment by rananna** [comment]
@casainho , The old repository is working fine, the new one resets randomly.
Very frustrating as so far I can't find the issue.
Have you managed to compare the two directories to see if there are sdk differences?

**Comment by casainho** [comment]
I tried to compare but I saw no differences. Please use Meld as I usually do, you can compare files or folders.

Give a look at the sdk_config.h, compare yourself to see if there are any differences. And you can always overwrite the SDK folder with the older one that you say works... if it works, good and then you can include on the PR.

https://meldmerge.org/

image

**Comment by casainho** [comment]
I forgot to say that I also changed the bootloader, I mean, I did not changed it but the bootloader is now also common to all projects... please give a look at the bootloader, can it the source of the issues??

**Comment by rananna** [comment]
@casinho, 
YES!!! I was using an older incorrect bootloader!!
Fixed it and everything works now.
Thanks! I will prepare the new PR

**Comment by rananna** [comment]
@casainho ,

No, spoke too soon.
I have a strange issue that maybe you can help with.
In my sdk_config.h , I need to have a define:
// <q> LED_SOFTBLINK_ENABLED  - led_softblink - led_softblink module
 #ifndef LED_SOFTBLINK_ENABLED
#define LED_SOFTBLINK_ENABLED 1
#endif
and this is of course correctly set in the include file which is in the remote include directory under firmware.
However, in led_softblink.c, there is the following:
#if NRF_MODULE_ENABLED(LED_SOFTBLINK)
#include <string.h>
#include "led_softblink.h"
#include "nrf_gpio.h"
etc...
Everything after the if statement is greyed out, indicating that LED_SOFTBLINK_ENABLED is not set!

I thought that you were grabbing the wrong sdk_config.h, but the makefile has:
PROJ_DIR := .
.
.
.
.
SDK_CONFIG_FILE := .$(PROJ_DIR)/config/sdk_config.h

so, this seems correct.
Is there some other reason why VS Code might use the wrong sdk_config.h?

**Comment by rananna** [comment]
I should have mentioned that  led_softblink.c, is NOT greyed out in the older remote repository,.

**Comment by casainho** [comment]
What you see grayed out on Code Studio is not the same the compiler sees.

You can use

#error test

On the source code to make sure code is passing there, as you will get a compiling error.

**Comment by rananna** [comment]
I just checked to be sure, if I right click on #if NRF_MODULE_ENABLED(LED_SOFTBLINK) and select go to definition, it brings up the wrong SDK config as attached.
sdk

**Comment by casainho** [comment]
Use CTRL-SHIFT to search for a word on all the project, to see where that define is used.

Also make sure you added common_firmware folder to the project so Code Studio will show you that folder and search on it.

**Comment by rananna** [comment]
So, why is it NOT greyed out in the older repository?

**Comment by rananna** [comment]
The define is needed for PWM LED control.

**Comment by rananna** [comment]
I'm not sure it's related, but EVERY single include file is UNDERLINED
include
 in the new repository,
see attached.
 when you put the mouse on it it says "cannot open source files:"  The strange thing is that it compiles OK!
Could this be related to the issue?

**Comment by rananna** [comment]
Isn't this now  wrong in c_cpp_properties.json as it is two directories up?
 "name": "nRF SDK 16.0.0",
                "includePath": [
                    "${workspaceFolder}/**"

**Comment by casainho** [comment]
I think there is a way, probably on that file, to say to Code Studio which defines are active - but that is tricky because it is totally different for which compiles uses, so beware of that.

**Pull request closed without merging**
