### PR TITLE
added ENTER + STANDBY pin DFU mode to match the bootloader firrmware

### PR DESCRIPTION
**Pull request by rananna**
As the title says.
@casainho , I have tested thourroughly the remote again and can find no problems with the new bootloader firmware.
Make sure you copot the hex file over to the remote bootloader directory before you build agai.
Perhaps you was working with an old bootloader when you had issues?
Anyway, try this build again and let me know.

### CODE REVIEW

**Comment by rananna** [comment]
I forgot to say that I will be creating a pull request for the bootloader soon, have checked your changes and they are fine. Some minor edits as will be explained in the PR

**Comment by casainho** [comment]
Thanks. Seems everything is in place to finish the bootloader.

Please test:
- LEDs (why not disable the LEDs at all, to save power and make code simple, because if bootloader is working we can always see it on Bluetooth!!)
- bootloader start using the board button
- update the bootloader itself.

**Comment by rananna** [comment]
Just made the PR for the bootloader and saw your comments.
"LEDs (why not disable the LEDs at all, to save power and make code simple, because if bootloader is working we can always see it on Bluetooth!!)"
The LEDs are useful to confirm the remote configuration visually (ie: ANT-LEV active, ANT CTRL active, brakes activated)
However, this creates a packaging issue if we need to see the LED in the final product
The best solution would be to connect the remote to the android app, we could verify configuration  that way and there would be no need for the  LEDS. I have no experience wwith maaking android apps, so I don't think I would be of much help with this.

"bootloader start using the board button"
This works fine

"update the bootloader itself."
Just tried this and works great. Updated same  and lower version number (useful if there is an issue) and also an incremented version and it also updates fine.

**Comment by casainho** [comment]
Great that the bootloader is almost finished!!

Sorry, I thought I was on bootloader repo. I mean that the bootloader could not use any LED at all, mainly to save power. Regular usage of bootloader will be to just start the user firmware, so, even better to let the LEDs states be defined by the user firmware.

I agree that LEDs can work similarly as the Garmin EBike remote and we have time to test / change user firmware, but bootloader is something that should be very stable.

**Comment by rananna** [comment]
Oops you are on the bootloader repo. I guess I had the remote on my mind.
Yes, we could disable the leds for the bootloader.
However, the brief red flash that shows you are in the bootloader is a nice visual feedback that doesn't use much pwr though. This flash happens in the remote when you reset to go into and out of bluetooth mode.
How about I keep this red flash for now, and eliminate the flashing leds during dfu?

**Comment by rananna** [comment]
On second thought, I could put this flash for visual feedback in the remote firmware.
I will remove all led feedback in the bootloader.
Do you agree?

**Comment by casainho** [comment]
Yes, please remove all LEDs for the bootloader.

**Pull request merged**
