### PR TITLE
Fixed pwr handling, added pwr analysis docs

### PR DESCRIPTION
**Pull request by rananna**
@casainho 
Merry Christmas!
I have been having fun play with my new toy, the Nordic PPK2 power profiler.
I used it to confirm the power modes for the remote control and confirmed that the POWER OFF mode draws 10 uA on average.
using the PPK2, I analysed the remote in various test scenarios and published the results in the docs.
To see the analysis, click on "battery considerations" from the main page.
I also put together a spreadsheet to estimate battery life, and with some fairly conservative assumptions, it looks like we can get at least a year of life from the remote. This is good news!

Also, I noticed that the POWER ON idle current will drop to 10 ua also IF (and only if) the remote cannot connect to any ANT devices (and of course bluetooth is off). This is IDENTICAL to the 10 uA found in POWER OFF mode.
POWER OFF mode, of course, causes a reset of the board, where POWER ON does not.
Since the normal mode of operation will be to cut the ANT connection after a ride is over by turning off the motor and powering down the edge display, maybe we do not need to implement POWER OFF?
I was a little disappointed that POWER OFF did not go below 10uA, but this appears to be a limitation of the s340 SD.
Without the SD, POWER OFF can be as little as 3-4uA

### CODE REVIEW

**Comment by rananna** [comment]
Forgot to mention that the pwr difference with a sd is that the lfclk is left running, even in power off mode, which probably accounts for the higher 10 uA current.

**Comment by casainho** [comment]
Good that you get that power profiler!! Congratulations on your work!!

What I like with the POWER OFF mode that resets the board, it that it will always starts from a clean state and that is the most tested case for us during development - if the system would hang because an issue let's say on ANT or Bluetooth code, we would need to remove the battery to force the reset of the system.

Maybe the power during POWER OFF and even POWER ON idle can't be better because the board has no RTC hardware and so the low frequency clock is derived from the high frequency clock which should take extra energy. Maybe this could be tested with an external RTC hardware connected to the board? Anyway, this would only be important for a custom board.

**Comment by casainho** [comment]
And there is a very important measure you could take, that is RGB LED consumption. The LED will be very important to give user feedback.

**Comment by rananna** [comment]
Will do.

**Comment by rananna** [comment]
Checked the dongle specs, it seems it does have a of crystal oscillator, labelled x2.
"6.5 32.768 kHz crystal
The nRF52840 Dongle is equipped with a 32.768 kHz crystal (X2) for high accuracy and low average power
consumption.
Note: The 32.768 kHz crystal (X2) is required for correct operation when using ANT/ANT+."
Not sure what is drawing power in system off mode.

**Comment by rananna** [comment]
Just for interest, I will also measure the maker diary board to confirm we made the right choice to switch.

**Comment by casainho** [comment]
Yes, my mistake. Both boards has the 32.768 kHz crystal.

And that measurements does not include any external hardware on the board? Are the measures only with the battery directly to the NRF52?

**Comment by rananna** [comment]
Yes to both.
The ppk2 is basically an ammeter in series with the coin battery cr2032 supply. No additional hardware is needed.
I see my PR has formatting issues for the battery analysis doc caused by missing spaces after ##.
This did not show up in the vc code preview.
I will fix and give you another PR

**Comment by casainho** [comment]
Ok, then we need to make sure that any extra hardware on our real board does not make any penalization.

**Comment by rananna** [comment]
Yes. 
However, I think we will not need anything else for the remote though.
Of course, the pwr tests were connected with the buttons connected to the gpios and we could use the onboard led for display in the packaged remote.
Was there something else planned to be added?

**Comment by casainho** [comment]
Nothing more. But now I understand that LED feedback will be important for user to know if TSDZ2 motor is enable or if not, and state of startup since the torque sensor ADC calibration is critical at startup!!! user can't touch the pedals, etc, etc

**Pull request merged**
