### PR TITLE
pwr management + cleaned code + readme videos

### PR DESCRIPTION
**Pull request by rananna**
@casainho , I have made the following changes to the remote control code:
1. pwr management in the idle loop and turns off ANT when bluetooth active. This not only saves power but is needed beecause ANT+ controls and  ANT LEV active at the same time conflicts with bluetooth
2. better long press button maanagement
3. bluetooth timeout added
4. readme videos added
5. uses new bootloader (PR not merged yet)

### CODE REVIEW

**Comment by casainho** [comment]
Keep the good work!!

I wounder if Bluetooth really does not work simultaneous with ANT, as I think we eventually, will need the Bluetooth for fast brake signal communication.

There are conflicts that I can´t solve with this PR, please look at it.

**Comment by rananna** [comment]
Well, it seems the issues with PRs are happening again.
I see a lot of changes to the code that need to be manually corrected for some reason.
I will try the same approach we used  the other day.
1. delete the repository
2 fork again
3 upload new code
4 create new PR

I hope we can figure out what is going wrong with PRs, this is painful.
Regarding the ANT issue with bluetooth, there is an interrupt conflict problem of some sort happening that I didn't bother to track down.
It seemed simpler to just turn off ANT when bluetooth is on as it saves power anyway
I will look into it.
I still hope ANT will be OK for brakes as an always on bluetooth will be bad on the battery life

**Comment by casainho** [comment]
Maybe the issue with PRs are that you do not update your branch with this base branch before doing the PR?

Yes, first we should try ANT for brakes and only after try Bluetooth. At least I am pretty sure it can be fast enough for our need.

**Comment by rananna** [comment]
I tried to update by simply initiating a PR from your repository to my repository. However this is where I see the same conflicts as you do.
Is there some other way to update in github?

**Pull request closed without merging**
